[package]
name = "fluent-concurrency"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { workspace = true }
fluent-wvr = { path = "../fluent-wvr" }
fluent-dag = { path = "../dag" }
serde = { workspace = true }
serde_json = { workspace = true }
bon = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
reqwest = { workspace = true }
common-core = { path = "../common-core", features = ["sqlite"] }
rusqlite = { workspace = true }
fastrand = { workspace = true }
internment = { workspace = true, features = ["arc", "serde"] }
futures-util = { workspace = true }
bytes = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
tempfile = { workspace = true }
fluent-wvr-testutil = { path = "../fluent-wvr-testutil" }

[lints]
workspace = true
