//! Rendering of downstream serving configs from a scanned GGUF layout:
//! the llama.cpp `models-preset.ini`, a LiteLLM `config.yaml`, and an aichat
//! config. Ported from `gguf_tool.py` (`write_llama_preset`,
//! `render_litellm_yaml`, `render_aichat_config`, `PARAM_KEY_MAP`).

#![allow(
    clippy::cast_possible_truncation,
    clippy::cast_precision_loss,
    clippy::cast_sign_loss,
    clippy::fn_params_excessive_bools,
    clippy::missing_errors_doc,
    clippy::too_many_arguments
)]

use std::fmt::Write as _;
use std::path::Path;

use serde_json::Value;

use super::gguf::{is_embedding_model, read_gguf_metadata, scan_gguf_models, GgufEntry};

/// Map from Ollama/`params.json` keys to llama-server CLI flag names.
/// Only scalar-valued keys are written; list values (e.g. `stop`) are skipped
/// because the preset INI parser does not accept them.
const PARAM_KEY_MAP: &[(&str, &str)] = &[
    // Sampling
    ("temperature", "temp"),
    ("top_k", "top-k"),
    ("top_p", "top-p"),
    ("min_p", "min-p"),
    ("presence_penalty", "presence-penalty"),
    ("repeat_penalty", "repeat-penalty"),
    ("frequency_penalty", "frequency-penalty"),
    ("repeat_last_n", "repeat-last-n"),
    ("mirostat", "mirostat"),
    ("mirostat_lr", "mirostat-lr"),
    ("mirostat_ent", "mirostat-ent"),
    ("typical_p", "typical-p"),
    ("seed", "seed"),
    // Context / prediction
    ("num_ctx", "ctx-size"),
    ("ctx_size", "ctx-size"),
    ("n_predict", "n-predict"),
    // Batching
    ("batch_size", "batch-size"),
    ("ubatch_size", "ubatch-size"),
    // Parallelism
    ("parallel", "parallel"),
    // GPU / offloading
    ("n_gpu_layers", "n-gpu-layers"),
    ("split_mode", "split-mode"),
    ("flash_attn", "flash-attn"),
    ("no_kv_offload", "no-kv-offload"),
    ("kv_offload", "kv-offload"),
    // MoE expert offloading
    ("n_cpu_moe", "n-cpu-moe"),
    ("cpu_moe", "cpu-moe"),
    // KV cache types
    ("cache_type_k", "cache-type-k"),
    ("cache_type_v", "cache-type-v"),
    // Memory management
    ("mlock", "mlock"),
    ("no_mmap", "no-mmap"),
    ("mmap", "mmap"),
    // RoPE
    ("rope_freq_base", "rope-freq-base"),
    ("rope_freq_scale", "rope-freq-scale"),
    ("rope_scaling", "rope-scaling"),
    // Idle / lifecycle
    ("keep_alive", "sleep-idle-seconds"),
    // Embedding
    ("embedding", "embedding"),
];

fn map_param_key(key: &str) -> &str {
    PARAM_KEY_MAP
        .iter()
        .find(|(k, _)| *k == key)
        .map_or(key, |(_, v)| v)
}

/// Render the llama.cpp multi-model preset INI.
///
/// Emits a `[*]` default section followed by one `[model]` section per
/// scanned model, each with the model path (relative to `gguf_dir`, prefixed
/// with `path_prefix` when given), optional `chat-template-file`/`mmproj`
/// companions, `params.json` values, GGUF-metadata RoPE flags, and an
/// `embedding = true` marker for embedding-only models.
pub fn render_llama_preset(gguf_dir: &Path, path_prefix: Option<&str>) -> String {
    let mut out = String::new();
    out.push_str("# llama.cpp multi-model preset\n");
    out.push_str("# Generated by coral-router\n");
    let _ = writeln!(out, "# models-dir = {}", gguf_dir.display());
    out.push('\n');

    // Default section — applied to every model unless overridden per-model.
    out.push_str("[*]\n");
    out.push_str("batch-size = 4096\n");
    out.push_str("ubatch-size = 1024\n");
    out.push_str("cache-type-k = q8_0\n");
    out.push_str("cache-type-v = q8_0\n");
    out.push_str("ctx-size = 8192\n");
    out.push_str("flash-attn = on\n");
    out.push_str("n-gpu-layers = 999\n");
    out.push_str("n-cpu-moe = 0\n");
    out.push_str("sleep-idle-seconds = 900\n");
    out.push_str("verbose = 0\n");
    out.push('\n');

    let models = scan_gguf_models(gguf_dir);
    let mut names: Vec<&str> = models.iter().map(|m| m.display.as_str()).collect();
    names.sort_unstable();
    names.dedup();

    for name in names {
        let model = models
            .iter()
            .find(|m| m.display == name)
            .expect("name collected from models");
        if !model.path.exists() {
            continue;
        }
        let model_dir = model.path.parent().unwrap_or_else(|| Path::new("."));

        let prefixed = |p: &Path| -> String {
            match path_prefix {
                Some(prefix) => format!(
                    "{prefix}/{}",
                    p.strip_prefix(gguf_dir).unwrap_or(p).display()
                ),
                None => p.display().to_string(),
            }
        };

        let _ = writeln!(out, "[{name}]");
        let _ = writeln!(out, "model = {}", prefixed(&model.path));

        // A template.txt companion, when present, takes precedence over the
        // chat template baked into the GGUF metadata. Emit it as
        // `chat-template-file` (NOT the literal `chat-template` key) so the
        // preset parser reads the file path from disk at model-load time.
        let template_path = model_dir.join("template.txt");
        if template_path.exists() {
            let _ = writeln!(out, "chat-template-file = {}", prefixed(&template_path));
        }

        let projector = model_dir.join("projector.gguf");
        if projector.exists() {
            let _ = writeln!(out, "mmproj = {}", prefixed(&projector));
        }

        // params.json values (temp, top_k, num_ctx, ...).
        let mut params_map: Vec<(String, String)> = Vec::new();
        if let Ok(text) = std::fs::read_to_string(model_dir.join("params.json")) {
            if let Ok(Value::Object(map)) = serde_json::from_str::<Value>(&text) {
                for (k, v) in map {
                    if matches!(v, Value::String(_) | Value::Number(_) | Value::Bool(_)) {
                        params_map.push((map_param_key(&k).to_string(), scalar_string(&v)));
                    }
                }
            }
        }

        // GGUF-metadata architecture flags (RoPE base/scale) — never override
        // ctx-size; params.json wins.
        let gguf_meta = read_gguf_metadata(&model.path);
        let arch = gguf_meta
            .get("general.architecture")
            .and_then(Value::as_str)
            .unwrap_or_default();
        let mut gguf_flags: Vec<(String, String)> = Vec::new();
        if !arch.is_empty() {
            let rope_base = gguf_meta
                .get(&format!("{arch}.rope.freq_base"))
                .or_else(|| gguf_meta.get("rope.freq_base"));
            if let Some(v) = rope_base {
                gguf_flags.push(("rope-freq-base".into(), scalar_string(v)));
            }
            let freq_scale = gguf_meta
                .get(&format!("{arch}.rope.freq_scale"))
                .or_else(|| gguf_meta.get("rope.freq_scale"));
            if let Some(v) = freq_scale {
                gguf_flags.push(("rope-freq-scale".into(), scalar_string(v)));
            }
        }

        for (k, v) in params_map {
            let _ = writeln!(out, "{k} = {v}");
        }
        for (k, v) in gguf_flags {
            let _ = writeln!(out, "{k} = {v}");
        }
        if is_embedding_model(name, model_dir) {
            out.push_str("embedding = true\n");
        }
        out.push('\n');
    }

    out
}

fn scalar_string(v: &Value) -> String {
    match v {
        Value::Bool(b) => {
            if *b {
                "true".into()
            } else {
                "false".into()
            }
        }
        Value::Number(n) => n.to_string(),
        Value::String(s) => s.clone(),
        _ => v.to_string(),
    }
}

/// Write `models-preset.ini` into `gguf_dir`.
pub fn write_models_preset(
    gguf_dir: &Path,
    path_prefix: Option<&str>,
) -> std::io::Result<std::path::PathBuf> {
    let content = render_llama_preset(gguf_dir, path_prefix);
    let preset_path = gguf_dir.join("models-preset.ini");
    std::fs::write(&preset_path, content)?;
    Ok(preset_path)
}

/// Render a LiteLLM `model_list` YAML pointing every model at the llama.cpp
/// server on :8080.
pub fn render_litellm_yaml(models: &[GgufEntry]) -> String {
    let mut out = String::from("model_list:\n");
    let mut names: Vec<&str> = models.iter().map(|m| m.display.as_str()).collect();
    names.sort_unstable();
    names.dedup();
    for name in names {
        out.push_str("  - model_name: ");
        out.push_str(name);
        out.push_str("\n    litellm_params:\n      model: llama.cpp/");
        out.push_str(name);
        out.push_str(
            "\n      api_base: http://localhost:8080\n      custom_llm_provider: openai\n",
        );
    }
    out
}

/// Render an aichat config pointing every model at the llama.cpp server.
pub fn render_aichat_config(models: &[GgufEntry]) -> String {
    let mut out = String::from(
        "model: litellm\nclients:\n- type: openai-compatible\n  name: llama-cpp\n  api_base: http://127.0.0.1:8080/v1\n  api_key: null\n  models:\n",
    );
    let mut names: Vec<&str> = models.iter().map(|m| m.display.as_str()).collect();
    names.sort_unstable();
    names.dedup();
    for name in names {
        out.push_str("  - name: ");
        out.push_str(name);
        out.push('\n');
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn write_gguf(path: &std::path::Path, arch: &str) {
        use std::io::Write;
        let mut f = std::fs::File::create(path).unwrap();
        f.write_all(b"GGUF").unwrap();
        f.write_all(&1u32.to_le_bytes()).unwrap();
        f.write_all(&0u64.to_le_bytes()).unwrap();
        f.write_all(&2u64.to_le_bytes()).unwrap();
        let write_kv_str = |f: &mut std::fs::File, key: &str, value: &str| {
            f.write_all(&(key.len() as u64).to_le_bytes()).unwrap();
            f.write_all(key.as_bytes()).unwrap();
            f.write_all(&8u32.to_le_bytes()).unwrap(); // string
            f.write_all(&(value.len() as u64).to_le_bytes()).unwrap();
            f.write_all(value.as_bytes()).unwrap();
        };
        write_kv_str(&mut f, "general.architecture", arch);
        let key = format!("{arch}.rope.freq_base");
        f.write_all(&(key.len() as u64).to_le_bytes()).unwrap();
        f.write_all(key.as_bytes()).unwrap();
        f.write_all(&6u32.to_le_bytes()).unwrap();
        f.write_all(&1_000_000.0f32.to_le_bytes()).unwrap();
    }

    #[test]
    fn preset_has_default_section_and_model_section() {
        let dir = tempfile::tempdir().unwrap();
        let model_dir = dir.path().join("library/code");
        std::fs::create_dir_all(&model_dir).unwrap();
        write_gguf(&model_dir.join("latest.gguf"), "llama");
        std::fs::write(
            model_dir.join("params.json"),
            r#"{"temperature": 0.7, "num_ctx": 8192}"#,
        )
        .unwrap();

        let content = render_llama_preset(dir.path(), None);
        assert!(content.contains("[*]"));
        assert!(content.contains("[code]"));
        assert!(content.contains("model = "));
        assert!(content.contains("temp = 0.7"));
        assert!(content.contains("ctx-size = 8192"));
        assert!(content.contains("rope-freq-base = 1000000.0"));
    }

    #[test]
    fn litellm_and_aichat_render_all_models() {
        let dir = tempfile::tempdir().unwrap();
        let model_dir = dir.path().join("abiray/x");
        std::fs::create_dir_all(&model_dir).unwrap();
        write_gguf(&model_dir.join("latest.gguf"), "llama");
        let models = scan_gguf_models(dir.path());
        let litellm = render_litellm_yaml(&models);
        assert!(litellm.contains("model_name: abiray/x"));
        assert!(litellm.contains("model: llama.cpp/abiray/x"));
        let aichat = render_aichat_config(&models);
        assert!(aichat.contains("name: abiray/x"));
    }
}
