[package]
autotests = false
autobenches = false
name = "fluent-knowledge"
version.workspace = true
edition.workspace = true

[dependencies]
common-core = { path = "../common-core" }
fluent-db = { path = "../db" }
blake3 = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
fluent-wvr-testutil = { path = "../fluent-wvr-testutil" }

[lints]
workspace = true
