[package]
name = "common-core"
version.workspace = true
edition.workspace = true

[features]
default = []
test-util = []
http = ["dep:reqwest"]
sqlite = ["dep:rusqlite", "dep:hnsw_rs", "dep:anndists"]

[dependencies]
bitvec = { workspace = true }
blake3 = { workspace = true }
fastrand = { workspace = true }
internment = { workspace = true, features = ["arc"] }
reqwest = { workspace = true, optional = true }
anndists = { workspace = true, optional = true }
hnsw_rs = { workspace = true, optional = true }
rusqlite = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
