#!/usr/bin/env python3
"""One-time generator for the English tag → UPOS map.

Loads the installed ``en_core_web_sm`` 3.8.0 model and extracts the
tag → POS mapping from its attribute_ruler patterns (the mechanism that sets
``token.pos`` from ``token.tag`` at inference time — the 56-entry tag map),
emitting ``src/spacy-rs/src/lang/en/tag_map.rs``.

Run:
    /tmp/opencode/spacy-venv/bin/python3 src/spacy-rs/tools/gen_en_tag_map.py
"""
from __future__ import annotations

import json

import en_core_web_sm  # noqa: E402

OUT = "src/spacy-rs/src/lang/en/tag_map.rs"

nlp = en_core_web_sm.load()
ar = nlp.get_pipe("attribute_ruler")

out = {}


def tag_str(t):
    if isinstance(t, str):
        return t
    if isinstance(t, dict):
        return tag_str(next(iter(t.values())))
    if isinstance(t, list):
        return tag_str(t[0])
    return None


for p in ar.patterns:
    attrs = p.get("attrs", {})
    pos = attrs.get("POS")
    if not pos:
        continue
    for pattern in p.get("patterns", []):
        toks = pattern if isinstance(pattern, list) else [pattern]
        for tok in toks:
            if isinstance(tok, dict) and "TAG" in tok:
                tag = tag_str(tok["TAG"])
                if tag:
                    out.setdefault(tag, pos)

print(f"{len(out)} tag → POS entries")

with open(OUT, "w") as f:
    f.write(
        "// @generated by src/spacy-rs/tools/gen_en_tag_map.py — do not edit.\n"
        "// English tag → UPOS map from en_core_web_sm 3.8.0\n"
        "// (attribute_ruler patterns: the mechanism that derives token.pos\n"
        f"// from token.tag), {len(out)} entries sorted by tag.\n"
        "\n"
        "pub const TAG_MAP: &[(&str, &str)] = &[\n"
    )
    for tag in sorted(out):
        f.write(
            f"    ({json.dumps(tag, ensure_ascii=False)}, "
            f"{json.dumps(out[tag], ensure_ascii=False)}),\n"
        )
    f.write("];\n")
print(f"wrote {OUT}")