#!/usr/bin/env python3
"""One-time generator for the English tokenizer data in spacy-rs.

Reads the pinned spaCy 3.8.15 checkout at ``/opt/src/nlp/spaCy`` (pure-Python
modules only: char_classes.py, punctuation.py, en/stop_words.py) and emits

- ``src/spacy-rs/src/lang/en/patterns.rs`` — the compiled prefix/suffix/infix
  affix patterns and the URL match pattern, translated to the fancy-regex
  dialect (``\\u{XXXX}``).
- ``src/spacy-rs/src/lang/en/stop_words.rs`` — the English stop-word set.

The tokenizer *exceptions* are generated by ``gen_en_exceptions.py`` once the
full spaCy package is importable (needs the compiled Cython extensions).

Run from the repo root:
    python3 src/spacy-rs/tools/gen_en_regexes.py
"""
from __future__ import annotations

import importlib.util
import ast
import json
import re
import sys
import types

SPACY = "/opt/src/nlp/spaCy/spacy"
OUT_EN = "src/spacy-rs/src/lang/en"
OUT_BASE = "src/spacy-rs/src/lang"


def load(name: str, path: str):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


def translate_to_fancy_regex(pattern: str) -> str:
    """Translate Python-`re` unicode escapes to the fancy-regex dialect.

    Python uses ``\\uXXXX`` / ``\\UXXXXXXXX``; fancy-regex uses ``\\u{XXXX}``.
    """

    def repl_u(m: re.Match) -> str:
        return "\\u{" + m.group(1) + "}"

    out = re.sub(r"\\u([0-9a-fA-F]{4})", repl_u, pattern)
    out = re.sub(r"\\U([0-9a-fA-F]{8})", repl_u, out)
    # sanity: every remaining backslash escape must be a known literal
    # (skip translated \\u{...} codepoint escapes)
    remainder = re.sub(r"\\u\{[0-9a-fA-F]+\}", "", out)
    for esc in set(re.findall(r"\\.", remainder)):
        if esc not in {
            "\\!", "\\$", "\\'", "\\(", "\\)", "\\*", "\\+", "\\.", "\\?",
            "\\[", "\\]", "\\{", "\\}", "\\-", "\\S", "\\d", "\\w", "\\s",
        }:
            raise SystemExit(f"unhandled escape {esc!r} in generated pattern")
    return out


def main() -> None:
    spacy = types.ModuleType("spacy")
    spacy.__path__ = []
    sys.modules["spacy"] = spacy
    spacy_lang = types.ModuleType("spacy.lang")
    spacy_lang.__path__ = []
    sys.modules["spacy.lang"] = spacy_lang
    spacy_lang_en = types.ModuleType("spacy.lang.en")
    spacy_lang_en.__path__ = []
    sys.modules["spacy.lang.en"] = spacy_lang_en

    char_classes = load("spacy.lang.char_classes", f"{SPACY}/lang/char_classes.py")
    base_punct = load("spacy.lang.punctuation", f"{SPACY}/lang/punctuation.py")
    # English overrides only the infixes (`spacy/lang/en/punctuation.py` — the
    # hyphen and `[:<>=/]` lookbehinds include `0-9`); prefixes/suffixes stay
    # the base module's.
    en_punct = load("spacy.lang.en.punctuation", f"{SPACY}/lang/en/punctuation.py")
    stop = load("spacy.lang.en.stop_words", f"{SPACY}/lang/en/stop_words.py")

    def compile_prefix(entries):
        return "|".join(["^" + p for p in entries if p.strip()])

    def compile_suffix(entries):
        return "|".join([p + "$" for p in entries if p.strip()])

    def compile_infix(entries):
        return "|".join([p for p in entries if p.strip()])

    prefix = translate_to_fancy_regex(compile_prefix(base_punct.TOKENIZER_PREFIXES))
    suffix = translate_to_fancy_regex(compile_suffix(base_punct.TOKENIZER_SUFFIXES))
    infix = translate_to_fancy_regex(compile_infix(en_punct.TOKENIZER_INFIXES))

    # Replicate spacy/lang/tokenizer_exceptions.py URL_PATTERN (pure string).
    ALPHA_LOWER = char_classes.ALPHA_LOWER
    url_pattern = (
        "^"
        r"(?:(?:[\w\+\-\.]{2,})://)?"
        r"(?:\S+(?::\S*)?@)?"
        r"(?:"
        r"(?!(?:10|127)(?:\.\d{1,3}){3})"
        r"(?!(?:169\.254|192\.168)(?:\.\d{1,3}){2})"
        r"(?!172\.(?:1[6-9]|2\d|3[0-1])(?:\.\d{1,3}){2})"
        r"(?:[1-9]\d?|1\d\d|2[01]\d|22[0-3])"
        r"(?:\.(?:1?\d{1,2}|2[0-4]\d|25[0-5])){2}"
        r"(?:\.(?:[1-9]\d?|1\d\d|2[0-4]\d|25[0-4]))"
        r"|"
        r"(?:"
        r"(?:"
        r"[A-Za-z0-9\u00a1-\uffff]"
        r"[A-Za-z0-9\u00a1-\uffff_-]{0,62}"
        r")?"
        r"[A-Za-z0-9\u00a1-\uffff]\."
        r")+"
        r"(?:[" + ALPHA_LOWER + r"]{2,63})"
        r")"
        r"(?::\d{2,5})?"
        r"(?:[/?#]\S*)?"
        r"$"
    ).strip()
    url = translate_to_fancy_regex(url_pattern)

    # Round-trip sanity: the untranslated joined patterns must compile under
    # Python re, proving the generator replicated the spaCy joins verbatim.
    def untranslate(pat: str) -> str:
        def repl(m: re.Match) -> str:
            digits = m.group(1)
            if len(digits) <= 4:
                return "\\u" + digits.zfill(4)
            return "\\U" + digits.zfill(8)

        return re.sub(r"\\u\{([0-9a-fA-F]+)\}", repl, pat)

    for label, pat in [("prefix", prefix), ("suffix", suffix), ("infix", infix)]:
        re.compile(untranslate(pat))
        print(f"{label}: len={len(pat)} compiled under python re")

    def wrap(label: str, value: str) -> str:
        return f"pub const {label}: &str = {json.dumps(value, ensure_ascii=False)};"

    affix_header = (
        "// @generated by src/spacy-rs/tools/gen_en_regexes.py — do not edit.\n"
        "// English affix patterns from spaCy 3.8.15\n"
        "// (spacy/lang/punctuation.py), compiled with the English Defaults\n"
        "// and translated to the fancy-regex dialect (\\u{XXXX}).\n"
        "#![allow(clippy::unicode_not_nfc)]\n"
    )
    affix_body = "\n\n".join(
        [
            wrap("PREFIX_PATTERN", prefix),
            wrap("SUFFIX_PATTERN", suffix),
            wrap("INFIX_PATTERN", infix),
        ]
    )
    with open(f"{OUT_EN}/patterns.rs", "w") as f:
        f.write(affix_header + "\n" + affix_body + "\n")

    url_header = (
        "// @generated by src/spacy-rs/tools/gen_en_regexes.py — do not edit.\n"
        "// The base URL_MATCH pattern from spaCy 3.8.15\n"
        "// (spacy/lang/tokenizer_exceptions.py), used by the base\n"
        "// like_url lexeme attribute. Translated to the fancy-regex dialect.\n"
        "#![allow(clippy::unicode_not_nfc)]\n"
    )
    with open(f"{OUT_BASE}/url.rs", "w") as f:
        f.write(url_header + "\n" + wrap("URL_PATTERN", url) + "\n")

    stops = sorted(stop.STOP_WORDS)
    with open(f"{OUT_EN}/stop_words.rs", "w") as f:
        f.write(
            "// @generated by src/spacy-rs/tools/gen_en_regexes.py — do not edit.\n"
            "// English stop words from spaCy 3.8.15 (spacy/lang/en/stop_words.py).\n"
            "\n"
            "pub const STOP_WORDS: &[&str] = &[\n"
        )
        for w in stops:
            f.write(f"    {json.dumps(w, ensure_ascii=False)},\n")
        f.write("];\n")

    # English number words from en/lex_attrs.py (_num_words / _ordinal_words).
    lex_attrs_src = open(f"{SPACY}/lang/en/lex_attrs.py").read()
    m = re.search(r"_num_words = (\[.*?\])", lex_attrs_src, re.S)
    ord_m = re.search(r"_ordinal_words = (\[.*?\])", lex_attrs_src, re.S)
    if not m or not ord_m:
        raise SystemExit("could not parse num/ordinal word lists from en/lex_attrs.py")
    num_words = ast.literal_eval(m.group(1))
    ordinal_words = ast.literal_eval(ord_m.group(1))
    with open(f"{OUT_EN}/num_words.rs", "w") as f:
        f.write(
            "// @generated by src/spacy-rs/tools/gen_en_regexes.py — do not edit.\n"
            "// English cardinal + ordinal number words from spaCy 3.8.15\n"
            "// (spacy/lang/en/lex_attrs.py `_num_words` / `_ordinal_words`),\n"
            "// used by the English LIKE_NUM lexeme attribute.\n"
            "\n"
            "pub const NUM_WORDS: &[&str] = &[\n"
        )
        for w in num_words:
            f.write(f"    {json.dumps(w, ensure_ascii=False)},\n")
        f.write("];\n\npub const ORDINAL_WORDS: &[&str] = &[\n")
        for w in ordinal_words:
            f.write(f"    {json.dumps(w, ensure_ascii=False)},\n")
        f.write("];\n")

    print(
        f"wrote {OUT_EN}/patterns.rs, {OUT_EN}/stop_words.rs, "
        f"{OUT_EN}/num_words.rs, {OUT_BASE}/url.rs"
    )

    # Base NORM exceptions from spacy/lang/norm_exceptions.py (pure Python),
    # applied by the Vocab to every language's lexeme norm getter
    # (vocab.pyx:34-36: BASE_NORMS wins over `lower`).
    norms_mod = load("spacy.lang.norm_exceptions", f"{SPACY}/lang/norm_exceptions.py")
    with open(f"{OUT_BASE}/norm_exceptions.rs", "w") as f:
        f.write(
            "// @generated by src/spacy-rs/tools/gen_en_regexes.py — do not edit.\n"
            "// Base NORM exceptions from spaCy 3.8.15 (spacy/lang/norm_exceptions.py),\n"
            "// consulted by every language's lexeme norm getter before `lower`.\n"
            "\n"
            "pub const BASE_NORMS: &[(&str, &str)] = &[\n"
        )
        for k, v in norms_mod.BASE_NORMS.items():
            f.write(
                f"    ({json.dumps(k, ensure_ascii=False)}, "
                f"{json.dumps(v, ensure_ascii=False)}),\n"
            )
        f.write("];\n")
    print(f"wrote {OUT_BASE}/norm_exceptions.rs")


if __name__ == "__main__":
    main()