#!/usr/bin/env python3
"""One-time generator for the English tokenizer exception rules.

Imports the fully built spaCy 3.8.15 from ``/opt/src/nlp/spaCy`` (editable
install in ``/tmp/opencode/spacy-venv``) and dumps the resolved
``TOKENIZER_EXCEPTIONS`` — the exact dict the ``Tokenizer`` loads, sorted by
key (the load order in ``_load_special_cases``) — as a Rust const array of
``(key, &[(orth, Option<norm>)])`` tuples.

Run:
    /tmp/opencode/spacy-venv/bin/python3 src/spacy-rs/tools/gen_en_exceptions.py
"""
from __future__ import annotations

import json
import sys

sys.path.insert(0, "/opt/src/nlp/spaCy")

from spacy.lang.en import TOKENIZER_EXCEPTIONS  # noqa: E402
from spacy.symbols import NORM, ORTH  # noqa: E402

OUT = "src/spacy-rs/src/lang/en/exceptions.rs"

rows = []
for key in sorted(TOKENIZER_EXCEPTIONS):
    substrings = TOKENIZER_EXCEPTIONS[key]
    toks = []
    for d in substrings:
        orth = d[ORTH]
        norm = d.get(NORM)
        toks.append((orth, norm))
    rows.append((key, toks))

total_tokens = sum(len(t) for _, t in rows)
print(f"{len(rows)} rules, {total_tokens} tokens")

with open(OUT, "w") as f:
    f.write(
        "// @generated by src/spacy-rs/tools/gen_en_exceptions.py — do not edit.\n"
        f"// English tokenizer exceptions from spaCy 3.8.15\n"
        f"// (spacy/lang/en/tokenizer_exceptions.py + BASE_EXCEPTIONS),\n"
        f"// {len(rows)} rules sorted by key (the `_load_special_cases` order).\n"
        "\n"
        "#![allow(clippy::type_complexity)]\n"
        "\n"
        "pub type ExcToken = (&'static str, Option<&'static str>);\n"
        "pub type ExcRule = (&'static str, &'static [ExcToken]);\n"
        "\n"
        "pub const RULES: &[ExcRule] = &[\n"
    )
    for key, toks in rows:
        inner = ", ".join(
            f"({json.dumps(o, ensure_ascii=False)}, "
            f"{'None' if n is None else 'Some(' + json.dumps(n, ensure_ascii=False) + ')'})"
            for o, n in toks
        )
        f.write(f"    ({json.dumps(key, ensure_ascii=False)}, &[{inner}]),\n")
    f.write("];\n")
print(f"wrote {OUT}")